#!/usr/bin/env bash

# Define variables
KEY_NAME="school"
KEY_BITS="4096"
KEY_PASSPHRASE="betty"

# Generate the RSA key pair
ssh-keygen -t rsa -b $KEY_BITS -C $KEY_NAME -f ~/.ssh/$KEY_NAME -N $KEY_PASSPHRASE

# Confirm successful key generation
if [ $? -eq 0 ]; then
  echo "RSA key pair generated successfully!"
  echo "Private key saved to: ~/.ssh/$KEY_NAME"
  echo "Public key saved to: ~/.ssh/$KEY_NAME.pub"
else
  echo "RSA key pair generation failed."
fi

